version: '3.9'
services:
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        container_name: menu-client
        ports:
            - 8080:8080
        depends_on:
            - server
        stdin_open: true
        tty: true
        volumes:
            - ./client/src:/app/src

    server:
        build:
            dockerfile: Dockerfile
            context: ./server
        container_name: menu-server
        ports:
            - 5000:5000
        restart: unless-stopped
        environment:
            - PORT=5000
            - MONGODB_URI=mongodb://server_db:27017/menuDB
        depends_on:
            - server_db

    server_db:
        image: mongo:latest
        container_name: menu-server-db
        volumes:
            - mongodb_server:/data/db

    mongo-seed:
        build: ./mongo-seed
        links:
            - server_db

volumes:
    mongodb_server:
